In [8]:
from rightmove_webscraper import RightmoveData

In [9]:
url = "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E475&minBedrooms=2&maxPrice=300000&propertyTypes=flat&includeSSTC=false&mustHave=&dontShow=retirement&furnishTypes=&keywords="
rm = RightmoveData(url)

In [10]:
rm.get_results.head()

,price,type,address,url,agent_url,postcode,full_postcode,number_bedrooms,search_date
0,279995,2 bedroom apartment for sale,"Salamander Street, \r\nLeith, \r\nEDINBURGH CI...",http://www.rightmove.co.uk/properties/14086451...,http://www.rightmove.co.uk/developer/branch/Ba...,EH6,EH6 7HR,2,2024-01-03 21:16:07.188413
1,300000,2 bedroom apartment for sale,"Gorgie Road, Edinburgh, EH11",http://www.rightmove.co.uk/properties/14184963...,http://www.rightmove.co.uk/estate-agents/agent...,EH11,NaN,2,2024-01-03 21:16:07.188413
2,300000,3 bedroom flat for sale,"320/1 Leith Walk, Leith, Edinburgh, EH6 5BU",http://www.rightmove.co.uk/properties/14311800...,http://www.rightmove.co.uk/estate-agents/agent...,EH6,EH6 5BU,3,2024-01-03 21:16:07.188413
3,300000,2 bedroom flat for sale,"Orchard Road, Comely Bank, Edinburgh, EH4",http://www.rightmove.co.uk/properties/13360974...,http://www.rightmove.co.uk/estate-agents/agent...,EH4,NaN,2,2024-01-03 21:16:07.188413
4,300000,2 bedroom apartment for sale,"Plot 41, Bridgeview Apartments, Lanark Road, E...",http://www.rightmove.co.uk/properties/14333280...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,NaN,2,2024-01-03 21:16:07.188413

In [5]:
rm.results_count

501

In [6]:
rm.average_price

231956.20758483035

In [7]:
rm.summary()

   number_bedrooms  count           mean
0                2    355  223555.538028
1                3    129  253091.852713
2                4     15  262266.333333

In [8]:
rm.summary(by="postcode")

   postcode  count           mean
0       EH6     71  244660.338028
1       EH4     55  234671.909091
2      EH12     40  238562.225000
3      EH16     38  238328.157895
4      EH11     36  236333.055556
5      EH17     32  237749.375000
6      EH21     27  226220.370370
7       EH5     24  213270.416667
8       EH7     22  222972.500000
9      EH14     20  221275.000000
10      EH8     19  247736.842105
11     EH22     12  206249.166667
12     EH15     11  242635.909091
13      EH3     10  254899.500000
14     EH20      9  186000.000000
15     EH10      8  255624.375000
16     EH13      6  189666.500000
17      EH1      4  259998.750000
18      EH9      3  258333.333333
19     EH25      2  212500.000000
20     EH18      2  137500.000000
21     EH29      1  239995.000000
22      EH2      1  275000.000000
23      G43      1  180000.000000
24       G5      1  230995.000000

In [11]:
rm.get_results.to_csv("rightmove.csv", index=False)

In [6]:
data = rm.get_results[rm.get_results['postcode'].isin(['EH3', 'EH8','EH10'])]

In [7]:
data.to_csv("rightmove2.csv", index=False)

In [11]:
data

,price,type,address,url,agent_url,postcode,full_postcode,number_bedrooms,search_date
14,300000,3 bedroom flat for sale,"62 3F3, Eyre Place, Edinburgh, EH3 5EJ",http://www.rightmove.co.uk/properties/13317271...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 5EJ,3,2024-01-03 20:39:19.579128
40,290000,2 bedroom flat for sale,"54 1F3, Merchiston Avenue, Edinburgh, EH10 4PA",http://www.rightmove.co.uk/properties/13876561...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,EH10 4PA,2,2024-01-03 20:39:19.579128
45,285000,2 bedroom flat for sale,"Silvermills, Edinburgh, EH3 5BF",http://www.rightmove.co.uk/properties/14178756...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 5BF,2,2024-01-03 20:39:19.579128
51,285000,2 bedroom flat for sale,"Clerk Street, Newington, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14152509...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
53,285000,2 bedroom flat for sale,"41/6 Lutton Place, Newington, Edinburgh, EH8 9PF",http://www.rightmove.co.uk/properties/13975447...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 9PF,2,2024-01-03 20:39:19.579128
62,280000,2 bedroom flat for sale,"8 2F2 Montague Street, Newington, Edinburgh, E...",http://www.rightmove.co.uk/properties/14237756...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,F2 Mo,2,2024-01-03 20:39:19.579128
80,275000,2 bedroom flat for sale,"Canongate, Old Town, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14238550...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
82,275000,4 bedroom maisonette for sale,"95 Mountcastle Terrace, Edinburgh, EH8 7SG",http://www.rightmove.co.uk/properties/14261032...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7SG,4,2024-01-03 20:39:19.579128
88,270000,2 bedroom flat for sale,"81/4 Grove Street, Edinburgh, EH3 8AB",http://www.rightmove.co.uk/properties/13391021...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 8AB,2,2024-01-03 20:39:19.579128
93,270000,2 bedroom flat for sale,"255/1 Canongate, EDINBURGH, EH8 8BQ",http://www.rightmove.co.uk/properties/14300121...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 8BQ,2,2024-01-03 20:39:19.579128
94,270000,2 bedroom ground floor flat for sale,"26/6 Gardner's Crescent, Edinburgh, EH3 8DF",http://www.rightmove.co.uk/properties/14310208...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 8DF,2,2024-01-03 20:39:19.579128
97,265000,2 bedroom flat for sale,"Montague Street, Newington, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14030517...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
102,265000,3 bedroom flat for sale,"17 Abercorn Court, Paisley Drive, Edinburgh, E...",http://www.rightmove.co.uk/properties/14140167...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7LP,3,2024-01-03 20:39:19.579128
104,265000,3 bedroom flat for sale,"20/5 Spittal Street, Edinburgh, EH3 9DT",http://www.rightmove.co.uk/properties/14316020...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 9DT,3,2024-01-03 20:39:19.579128
108,263000,2 bedroom ground floor flat for sale,"4A Meadowbank Terrace, Meadowbank, Edinburgh, ...",http://www.rightmove.co.uk/properties/13704921...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7AR,2,2024-01-03 20:39:19.579128
114,259995,2 bedroom flat for sale,"10/10 Falcon Road West, Morningside, Edinburgh...",http://www.rightmove.co.uk/properties/13610375...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,EH10 4AQ,2,2024-01-03 20:39:19.579128
117,259000,2 bedroom flat for sale,"25/2 Tarvit Street, Edinburgh, EH3",http://www.rightmove.co.uk/properties/14216045...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,NaN,2,2024-01-03 20:39:19.579128
124,250000,2 bedroom flat for sale,"1/1 Bulls Close, 100 Canongate, Old Town, Edin...",http://www.rightmove.co.uk/properties/14077635...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
128,250000,2 bedroom apartment for sale,"17 (3F2) Millar Crescent, Morningside, Edinbur...",http://www.rightmove.co.uk/properties/14219457...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,EH10 5HN,2,2024-01-03 20:39:19.579128
130,250000,2 bedroom flat for sale,"10 1F2, Craiglea Drive, Edinburgh, EH10 5PA",http://www.rightmove.co.uk/properties/14061959...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,EH10 5PA,2,2024-01-03 20:39:19.579128
135,250000,2 bedroom flat for sale,"Gilmore Place, Bruntsfield, Edinburgh, EH3",http://www.rightmove.co.uk/properties/14249709...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,NaN,2,2024-01-03 20:39:19.579128
140,249995,2 bedroom ground floor flat for sale,"8/2 Tarvit Street, Edinburgh EH3 9JY",http://www.rightmove.co.uk/properties/14138659...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 9JY,2,2024-01-03 20:39:19.579128
147,245000,2 bedroom flat for sale,"30 2F2 Balcarres Street, Morningside, Edinburg...",http://www.rightmove.co.uk/properties/86542770...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,F2 Ba,2,2024-01-03 20:39:19.579128
153,240000,2 bedroom flat for sale,"Northfield Heights, Northfield, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14157155...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
180,225000,4 bedroom flat for sale,"12 (1F2), Buckstone Terrace, Edinburgh, EH10 6PZ",http://www.rightmove.co.uk/properties/14316134...,http://www.rightmove.co.uk/estate-agents/agent...,EH10,EH10 6PZ,4,2024-01-03 20:39:19.579128
181,225000,2 bedroom ground floor flat for sale,"47 Northfield Broadway, Edinburgh, EH8 7QE",http://www.rightmove.co.uk/properties/14285510...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7QE,2,2024-01-03 20:39:19.579128
183,225000,2 bedroom flat for sale,"2 (3F1) Piershill Terrace, EDINBURGH, EH8 7ES",http://www.rightmove.co.uk/properties/14217098...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7ES,2,2024-01-03 20:39:19.579128
212,210000,2 bedroom flat for sale,"Gilmore Place, Bruntsfield, Edinburgh, EH3",http://www.rightmove.co.uk/properties/14038193...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,NaN,2,2024-01-03 20:39:19.579128
215,209000,2 bedroom flat for sale,"24 Piersfield Terrace, Edinburgh, EH8",http://www.rightmove.co.uk/properties/13197934...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
231,200000,2 bedroom flat for sale,"133/2 Piersfield Terrace, Piershill, Edinburgh...",http://www.rightmove.co.uk/properties/14299741...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,EH8 7BS,2,2024-01-03 20:39:19.579128
242,190000,2 bedroom flat for sale,"18/1 Hillend Place, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14112979...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128
243,190000,2 bedroom flat for sale,"2/13 Ponton Street, Fountainbridge, Edinburgh,...",http://www.rightmove.co.uk/properties/13999040...,http://www.rightmove.co.uk/estate-agents/agent...,EH3,EH3 9QQ,2,2024-01-03 20:39:19.579128
299,150000,2 bedroom flat for sale,"1/8 Northfield Drive, Edinburgh, EH8",http://www.rightmove.co.uk/properties/14199281...,http://www.rightmove.co.uk/estate-agents/agent...,EH8,NaN,2,2024-01-03 20:39:19.579128